### ISSUE TITLE
Ligatures on Linux system font renders `s` character unexpectedly

### ISSUE THREAD

**Issue by rootwork** [harrycresswell/harry#11]
Assuming this isn't intentional, I thought I'd let you know that the ligatures in your fonts are rendering every `s` as a stylized `f`. I'm on Linux Mint 20.3, Firefox 103.0.2. Guessing it's something about how the Linux system font(s) respond to some of the discretionary ligatures.

![2022-08-12_17-09](https://user-images.githubusercontent.com/79733/184459023-c232c71d-7060-426d-8319-b04c43804600.png)

(It's on body text too, not just headers.)

**Comment by harrycresswell** [comment]
Hi @rootwork, thanks a lot for letting me know about this. I’ve removed font feature settings from my CSS, which probably didn’t need to be in there seeing as sans serif defaults. That may have been causing the issue. How’s it looking now? Cheers!
